name: gestordelivros
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0       # Banco de dados SQL local
  path: ^1.9.0          # Ajuda a achar o caminho dos arquivos no celular
  provider: ^6.1.1      # Gerencia o estado (para a tela atualizar sozinha)
  intl: ^0.19.0         # Para formatar datas e moedas
  google_fonts: ^6.1.0  # Fontes bonitas e modernas
  image_picker: ^1.0.7
  share_plus: ^9.0.0     # <--- Para Exportar (Compartilhar o arquivo)
  file_picker: ^8.0.0    # <--- Para Importar (Buscar o arquivo no celular)
  flutter_rating_bar: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # Suporte a Androids mais novos
  adaptive_icon_background: "#FFFFFF" # Cor de fundo (se o icone for transparente)
  adaptive_icon_foreground: "assets/icon.png"
